### PR TITLE
Add buttons to get the app

### PR DESCRIPTION
**Pull request by Poussinou**
This PR adds two buttons to get the app easily on F-Droid and Google Play Store

Thanks for this app

### CODE REVIEW

**Comment by vishesh** [comment]
Thanks. Good idea. Just couple of comments -

1. I think getting those images a bit above would be great, particularly for people on mobile devices. If possible are there smaller images that can align well with those "Build" shield images below our main header? What do you think?
2. You have used HTML for inserting images. Use Markdown syntax. You can find how to use that in the README itself where we added the badges, or try this guide https://guides.github.com/features/mastering-markdown/

**Comment by Poussinou** [comment]
Maybe the "smaller images" you're asking for are somewhere on the web but I never heard about it. The buttons at the top of the README.md can be a goog idear you're right, especially for somebody using Octodroid (for example) like me.

Problem with the markdown language is that I cannot easily resize the badge, have a look on the changes I did.

**Comment by vishesh** [comment]
Ok. Seems like there is no way to scale images in markdown. Default size is just too big. Could you please use HTML version again, put it on top with scaling so that it aligns well with other badges at top.

Also, I suggest SVG images if they are available. Otherwise PNGs are just fine :)

Thanks again!

**Comment by vishesh** [comment]
@Poussinou Looks good. Thank you!

**Pull request closed without merging**
